# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selector_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dataLoadingGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.dataLoadingGroup.setGeometry(QtCore.QRect(10, 29, 781, 91))
        self.dataLoadingGroup.setObjectName("dataLoadingGroup")
        self.loadAllLeaguesButton = QtWidgets.QPushButton(self.dataLoadingGroup)
        self.loadAllLeaguesButton.setGeometry(QtCore.QRect(10, 40, 141, 27))
        self.loadAllLeaguesButton.setObjectName("loadAllLeaguesButton")
        self.leaguesComboBox = QtWidgets.QComboBox(self.dataLoadingGroup)
        self.leaguesComboBox.setGeometry(QtCore.QRect(250, 40, 221, 25))
        self.leaguesComboBox.setObjectName("leaguesComboBox")
        self.leaguesComboBox.addItem("")
        self.leaguesComboBox.addItem("")
        self.leaguesComboBox.addItem("")
        self.leaguesComboBox.addItem("")
        self.leaguesComboBox.addItem("")
        self.leagueSelectorLabel = QtWidgets.QLabel(self.dataLoadingGroup)
        self.leagueSelectorLabel.setGeometry(QtCore.QRect(280, 10, 161, 20))
        self.leagueSelectorLabel.setObjectName("leagueSelectorLabel")
        self.loadLeagueButton = QtWidgets.QPushButton(self.dataLoadingGroup)
        self.loadLeagueButton.setGeometry(QtCore.QRect(480, 40, 71, 27))
        self.loadLeagueButton.setObjectName("loadLeagueButton")
        self.pushButton = QtWidgets.QPushButton(self.dataLoadingGroup)
        self.pushButton.setGeometry(QtCore.QRect(660, 40, 111, 27))
        self.pushButton.setObjectName("pushButton")
        self.mainTextDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.mainTextDisplay.setGeometry(QtCore.QRect(10, 140, 781, 401))
        self.mainTextDisplay.setObjectName("mainTextDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataLoadingGroup.setTitle(_translate("MainWindow", "DATA LOADING"))
        self.loadAllLeaguesButton.setText(_translate("MainWindow", "Load All Leagues"))
        self.leaguesComboBox.setItemText(0, _translate("MainWindow", "England - Premier League"))
        self.leaguesComboBox.setItemText(1, _translate("MainWindow", "England - Championship"))
        self.leaguesComboBox.setItemText(2, _translate("MainWindow", "England - League 1"))
        self.leaguesComboBox.setItemText(3, _translate("MainWindow", "England - League 2"))
        self.leaguesComboBox.setItemText(4, _translate("MainWindow", "England - Conference"))
        self.leagueSelectorLabel.setText(_translate("MainWindow", "LEAGUE SELECTOR"))
        self.loadLeagueButton.setText(_translate("MainWindow", "Load"))
        self.pushButton.setText(_translate("MainWindow", "Write to Excel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
